# Generated by Django 5.2.9 on 2025-12-15 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_papers",
                to="exam.section",
            ),
        ),
        migrations.AlterField(
            model_name="questionpaper",
            name="subsection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_papers",
                to="exam.subsection",
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq_single", "MCQ (Single Answer)"),
                            ("mcq_multiple", "MCQ (Multiple Answers)"),
                            ("subjective", "Subjective"),
                            ("numeric", "Numeric"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True, help_text="For MCQ: List of options", null=True
                    ),
                ),
                (
                    "answer",
                    models.JSONField(
                        blank=True,
                        help_text="Correct answer(s) as list or value",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="question_images/"
                    ),
                ),
                (
                    "question_paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exam.questionpaper",
                    ),
                ),
            ],
        ),
    ]
