# Generated by Django 5.2.9 on 2025-12-15 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_questionpaper_section_alter_questionpaper_subsection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_papers",
                to="exam.exam",
            ),
        ),
    ]
