# Generated by Django 5.2.9 on 2025-12-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0003_questionpaper_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="has_two_subsections",
            field=models.BooleanField(
                default=False,
                help_text="Does this exam have two levels of subsections?",
            ),
        ),
    ]
