# Generated by Django 5.2 on 2025-12-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0004_exam_has_two_subsections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="question",
            name="options",
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(
                blank=True,
                help_text="For subjective/numeric",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_option",
            field=models.CharField(
                blank=True,
                help_text="A, B, C, D or comma separated for multiple",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="marks",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="question",
            name="negative_marks",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="option_a",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_b",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_c",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_d",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
