# Generated by Django 5.2 on 2025-12-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0005_remove_question_answer_remove_question_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpaper",
            name="duration",
            field=models.PositiveIntegerField(
                default=60, help_text="Duration in minutes"
            ),
        ),
    ]
