# Generated by Django 5.2 on 2025-12-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0008_question_exam_question_section_question_subsection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="questionpaper",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
