# Generated by Django 5.2 on 2025-12-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="post_type",
            field=models.CharField(
                choices=[("blog", "Blog Post"), ("notes", "Study Notes")],
                default="blog",
                max_length=10,
            ),
        ),
    ]
